services:
  configurator_module:
    build:
      context: ./backend/FAST-IBAN_Project/
      dockerfile: ./configurator/Dockerfile
      args:
        CDSAPI_URL: ${CDSAPI_URL}
        CDSAPI_KEY: ${CDSAPI_KEY}
    container_name: configurator_container
    env_file:
      - .env
    volumes:
      - config_data:/app/config
    stdin_open: true
    tty: true
    working_dir: /app

  rabbitmq:
    image: rabbitmq:3-management  # Incluye la interfaz web de administración
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"  # Puerto para la comunicación entre servicios
      - "15672:15672"  # Puerto para la interfaz de administración
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistencia de datos

  # handler_module:
  #   build:
  #     context: ./backend/FAST-IBAN_Project/
  #     dockerfile: ./handler/Dockerfile
  #   container_name: handler_container
  #   volumes:
  #     - ./backend/FAST-IBAN_Project:/app
  #     - out_data:/app/out
  #   stdin_open: true
  #   tty: true
  #   working_dir: /app

  # execution_module:
  #   build:
  #     context: ./backend/FAST-IBAN_Project/
  #     dockerfile: ./execution/Dockerfile
  #   container_name: execution_container
  #   volumes:
  #     - ./backend/FAST-IBAN_Project:/app
  #     - out_data:/app/out
  #   stdin_open: true
  #   tty: true
  #   working_dir: /app

  # visualization_module:
  #   build:
  #     context: ./backend/FAST-IBAN_Project/
  #     dockerfile: ./visualization/Dockerfile
  #   container_name: visualization_container
  #   volumes:
  #     - ./backend/FAST-IBAN_Project:/app
  #     - out_data:/app/out
  #   stdin_open: true
  #   tty: true
  #   working_dir: /app

  # tracking_module:
  #   build:
  #     context: ./backend/FAST-IBAN_Project/
  #     dockerfile: ./tracking/Dockerfile
  #   container_name: tracking_container
  #   volumes:
  #     - ./backend/FAST-IBAN_Project:/app
  #     - out_data:/app/out
  #   stdin_open: true
  #   tty: true
  #   working_dir: /app

volumes:
  out_data:
    driver: local
  in_data:
    driver: local
  config_data:
    driver: local
  rabbitmq_data:
    driver: local