services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    env_file:
      - .env
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  configurator_module:
    build:
      context: ./backend/FAST-IBAN_Project/
      dockerfile: ./configurator/Dockerfile
      args:
        CDSAPI_URL: ${CDSAPI_URL}
        CDSAPI_KEY: ${CDSAPI_KEY}
    container_name: configurator_container
    depends_on:
      - rabbitmq
    env_file:
      - .env
    volumes:
      - config_data:/app/config
    stdin_open: true
    tty: true
    working_dir: /app

  handler_module:
    build:
      context: ./backend/FAST-IBAN_Project/
      dockerfile: ./handler/Dockerfile
    container_name: handler_container
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - configurator_module
    volumes:
      - config_data:/app/config
      # - out_data:/app/out
    stdin_open: true
    tty: true
    working_dir: /app

  execution_module:
    build:
      context: ./backend/FAST-IBAN_Project/
      dockerfile: ./execution/Dockerfile
    container_name: execution_container
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - configurator_module
      - handler_module
    volumes:
      - config_data:/app/config
      - out_data:/app/out
    stdin_open: true
    tty: true
    working_dir: /app

  # visualization_module:
  #   build:
  #     context: ./backend/FAST-IBAN_Project/
  #     dockerfile: ./visualization/Dockerfile
  #   container_name: visualization_container
  #   volumes:
  #     - ./backend/FAST-IBAN_Project:/app
  #     - out_data:/app/out
  #   stdin_open: true
  #   tty: true
  #   working_dir: /app

  # tracking_module:
  #   build:
  #     context: ./backend/FAST-IBAN_Project/
  #     dockerfile: ./tracking/Dockerfile
  #   container_name: tracking_container
  #   volumes:
  #     - ./backend/FAST-IBAN_Project:/app
  #     - out_data:/app/out
  #   stdin_open: true
  #   tty: true
  #   working_dir: /app

volumes:
  out_data:
    driver: local
  config_data:
    driver: local
  rabbitmq_data:
    driver: local