services:
  nest_api:
    build:
      context: ./backend/nestjs
      dockerfile: Dockerfile
    container_name: nest_api_container
    env_file: .env
    environment:
      DB_HOST: postgres
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

  configurator_module:
    build:
      context: ./backend/FAST-IBAN_Project/
      dockerfile: ./configurator/Dockerfile
      args:
        CDSAPI_URL: ${CDSAPI_URL}
        CDSAPI_KEY: ${CDSAPI_KEY}
    container_name: configurator_container
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_started
    volumes:
      - config_data:/app/config
    stdin_open: true
    tty: true
    working_dir: /app
    networks:
      - app-network
    restart: unless-stopped

  handler_module:
    build:
      context: ./backend/FAST-IBAN_Project/
      dockerfile: ./handler/Dockerfile
    container_name: handler_container
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_started
      configurator_module:
        condition: service_started
    volumes:
      - config_data:/app/config
    stdin_open: true
    tty: true
    working_dir: /app
    networks:
      - app-network
    restart: unless-stopped

  execution_module:
    build:
      context: ./backend/FAST-IBAN_Project/
      dockerfile: ./execution/Dockerfile
    container_name: execution_container
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_started
      handler_module:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - config_data:/app/config
      - out_data:/app/out
    stdin_open: true
    tty: true
    working_dir: /app
    networks:
      - app-network
    restart: unless-stopped

  visualization_module:
    build:
      context: ./backend/FAST-IBAN_Project/
      dockerfile: ./visualization/Dockerfile
    container_name: visualization_container
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_started
      handler_module:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - config_data:/app/config
      - out_data:/app/out
    stdin_open: true
    tty: true
    working_dir: /app
    networks:
      - app-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    env_file: .env
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres_container
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    env_file: .env
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres_container
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file: .env
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    restart: unless-stopped

  minio-init:
    image: minio/minio:latest
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://${MINIO_ENDPOINT} ${MINIO_USER} ${MINIO_PASSWORD} &&
        mc mb local/${MINIO_BUCKET}
      "
    networks:
      - app-network

  cron-cleanup:
    build:
      context: ./cron_cleanup
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - TZ=Europe/Madrid
    networks:
      - app-network
    restart: unless-stopped

volumes:
  out_data:
  config_data:
  rabbitmq_data:
  postgres_data:
  minio_data:

networks:
  app-network:
    driver: bridge
