name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonaci칩n completa para mejor an치lisis

      # Instalar Python y herramientas para an치lisis Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # o cualquier linter que uses

      # Instalar herramientas para C
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang

      # Ejecutar an치lisis SonarQube con el token
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
